use serde_json::{json, Value};

use super::args::{PROPOSAL_ID_PATTERN, WRITE_CONTENT_TYPES};
use super::automation_policy::{policy_for_mcp_tool, AutomationDecision, ToolAutomationPolicy};
use super::supports_local_path_disclosure;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(in crate::mcp) struct MutatingToolPolicy {
    tool_name: &'static str,
    scope_policy: &'static str,
    evidence_policy: &'static str,
    audit_policy: &'static str,
    replay_policy: &'static str,
}

const MUTATING_TOOL_POLICIES: &[MutatingToolPolicy] = &[
    MutatingToolPolicy {
        tool_name: "import_source",
        scope_policy: "import-root allowlist",
        evidence_policy: "source evidence is generated by import",
        audit_policy: "import job and source records",
        replay_policy: "duplicate source/path behavior is tracked by import job/source IDs",
    },
    MutatingToolPolicy {
        tool_name: "import_cancel",
        scope_policy: "workspace and live job scope",
        evidence_policy: "not applicable",
        audit_policy: "import job cancellation state",
        replay_policy: "terminal jobs remain terminal",
    },
    MutatingToolPolicy {
        tool_name: "import_retry_graph",
        scope_policy: "workspace and source/job scope",
        evidence_policy: "requires citation-ready source evidence",
        audit_policy: "import job graph retry state",
        replay_policy: "retry availability is controlled by persisted graph retry metadata",
    },
    MutatingToolPolicy {
        tool_name: "graph_patch_apply",
        scope_policy: "workspace, source, and evidence scope",
        evidence_policy: "required before write and per changed record",
        audit_policy: "agent_graph_patch_apply graph materialization event",
        replay_policy: "record IDs are upserted only within validated source/evidence scope",
    },
    MutatingToolPolicy {
        tool_name: "write_propose",
        scope_policy: "workspace scope",
        evidence_policy: "evidence refs required before staging",
        audit_policy: "validated proposal record",
        replay_policy: "new proposalId per accepted proposal payload",
    },
    MutatingToolPolicy {
        tool_name: "write_commit",
        scope_policy: "workspace and proposal scope",
        evidence_policy: "proposal evidence revalidated before commit",
        audit_policy: "MemoryAccepted brain event and committed proposal status",
        replay_policy:
            "already committed, rejected, or missing proposal IDs fail with proposal_state",
    },
    MutatingToolPolicy {
        tool_name: "write_commit_all",
        scope_policy: "workspace and explicit proposal list scope",
        evidence_policy: "each proposal evidence is revalidated before commit",
        audit_policy: "per-proposal MemoryAccepted brain event on success",
        replay_policy: "per-item committed or failed result with errorCategory",
    },
    MutatingToolPolicy {
        tool_name: "write_reject",
        scope_policy: "workspace and proposal scope",
        evidence_policy: "not applicable",
        audit_policy: "rejected proposal status without brain event",
        replay_policy:
            "already rejected or missing proposal IDs are stable proposal_state failures",
    },
];

pub(super) fn tool_definitions() -> Vec<Value> {
    vec![
        tool_definition(
            "import_source",
            "Start importing an allowlisted local document into Etyma and return an import job for polling.",
            json!({
                "sourcePath": { "type": "string", "description": "Path to a local PDF, DOCX, DOC, Markdown, or image file under ETYMA_MCP_ALLOWED_IMPORT_ROOTS." },
                "name": { "type": "string", "description": "Optional display/output name for the imported source." },
                "format": { "type": "string", "enum": ["pdf", "docx", "doc", "markdown", "image"], "description": "Optional import format. Defaults to extension inference." },
                "skipGraphGeneration": { "type": "boolean", "description": "Skip provider-backed graph/wiki generation after citation-ready import. Defaults to false; citation readiness is reported before graph readiness." },
            }),
            vec!["sourcePath"],
            false,
        ),
        tool_definition(
            "import_status",
            "Poll a Etyma import job by jobId, or recover persisted import status by sourceId.",
            json!({
                "jobId": { "type": "string", "description": "Import job ID returned by import_source." },
                "sourceId": { "type": "string", "description": "Persisted source ID fallback when the live MCP job registry is gone." },
            }),
            Vec::new(),
            true,
        ),
        tool_definition(
            "import_cancel",
            "Request cancellation for a Etyma import job.",
            json!({
                "jobId": { "type": "string", "description": "Import job ID returned by import_source." },
            }),
            vec!["jobId"],
            false,
        ),
        tool_definition(
            "import_retry_graph",
            "Retry graph/wiki materialization for a citation-ready Etyma import job without reparsing the source.",
            json!({
                "jobId": { "type": "string", "description": "Import job ID returned by import_source." },
                "sourceId": { "type": "string", "description": "Persisted source ID fallback when the live MCP job registry is gone." },
            }),
            Vec::new(),
            false,
        ),
        tool_definition(
            "get_context_pack",
            "Build an agent-ready document context pack with selected sources, evidence, findings, warnings, and retrieval trace.",
            json!({
                "query": { "type": "string", "description": "Task or question to build context for." },
                "nodeId": { "type": "string", "description": "Optional selected graph node ID used as a retrieval bias, not as a full graph export." },
                "budget": { "type": "integer", "minimum": 1, "description": "Approximate token budget." },
            }),
            vec!["query"],
            true,
        ),
        tool_definition(
            "read_context_pack",
            "Read the latest persisted context pack, or a specific pack by packId. Context Pack v1 is projected to the v0 compatibility shape for this reader.",
            json!({
                "packId": { "type": "string", "description": "Optional packId under context_packs/. Defaults to the latest context_pack.json." },
            }),
            Vec::new(),
            true,
        ),
        tool_definition(
            "search_documents",
            "Search local Etyma document context artifacts and return ranked evidence-backed IDs.",
            json!({
                "query": { "type": "string", "description": "Search query." },
                "limit": { "type": "integer", "minimum": 1, "description": "Maximum result count." },
            }),
            vec!["query"],
            true,
        ),
        tool_definition(
            "search_brain",
            "Compatibility alias for search_documents.",
            json!({
                "query": { "type": "string", "description": "Search query." },
                "limit": { "type": "integer", "minimum": 1, "description": "Maximum result count." },
            }),
            vec!["query"],
            true,
        ),
        tool_definition(
            "read_source",
            "Read an immutable source record with adjacent wiki and evidence refs.",
            json!({
                "sourceId": { "type": "string", "description": "Source ID returned by search_documents or get_context_pack." },
            }),
            vec!["sourceId"],
            true,
        ),
        tool_definition(
            "read_page_evidence",
            "Read source evidence refs for a source, optionally narrowed to one 1-based page.",
            json!({
                "sourceId": { "type": "string", "description": "Source ID returned by search_documents or get_context_pack." },
                "page": { "type": "integer", "minimum": 1, "description": "Optional 1-based page number." },
            }),
            vec!["sourceId"],
            true,
        ),
        tool_definition(
            "read_wiki_page",
            "Read a generated or saved-back wiki page by repo-relative path.",
            json!({
                "path": { "type": "string", "description": "Wiki page path returned by search_brain or get_context_pack." },
            }),
            vec!["path"],
            true,
        ),
        tool_definition(
            "read_node",
            "Read a graph node with its evidence and adjacent relations.",
            json!({
                "nodeId": { "type": "string", "description": "Graph node ID returned by search_brain or get_context_pack." },
            }),
            vec!["nodeId"],
            true,
        ),
        tool_definition(
            "read_recent_events",
            "Read append-only graph loop events, optionally filtered by run, source, node, edge, claim, memory, or change type.",
            json!({
                "limit": { "type": "integer", "minimum": 1, "description": "Maximum event count." },
                "runId": { "type": "string", "description": "Filter by ingest run, source run, caused-by event, or payload runId." },
                "sourceRef": { "type": "string", "description": "Filter by source ID or markdown/source path ref." },
                "nodeId": { "type": "string", "description": "Filter by node ref or target node ID." },
                "edgeId": { "type": "string", "description": "Filter by edge/relation ref or target edge ID." },
                "claimId": { "type": "string", "description": "Filter by claim ref or target claim ID." },
                "memoryId": { "type": "string", "description": "Filter by memory ref or target memory ID." },
                "changeType": { "type": "string", "description": "Filter by event type, operation type, or payload changeType." },
            }),
            Vec::new(),
            true,
        ),
        tool_definition(
            "read_graph_history",
            "List prior materialized graph states, or inspect opt-in lifecycle history for a graph node, relation, or wiki page.",
            json!({
                "limit": { "type": "integer", "minimum": 1, "description": "Maximum graph state or record version count." },
                "recordKind": { "type": "string", "enum": ["node", "relation", "wiki_page"], "description": "Optional record history kind. Use with recordId for node/relation/wiki_page, or omit with wikiPath." },
                "recordId": { "type": "string", "description": "Logical graph node ID, relation ID, or wiki page ID for lifecycle history." },
                "wikiPath": { "type": "string", "description": "Wiki page path for lifecycle history, such as wiki/index.md." },
                "includeDiff": { "type": "boolean", "description": "Include stored wiki revision diff JSON when reading wiki page history. Defaults to false." },
            }),
            Vec::new(),
            true,
        ),
        tool_definition(
            "read_graph_snapshot",
            "Read the latest completed materialized graph/wiki snapshot and its loading paths for UI, MCP, and agent consumers.",
            json!({}),
            Vec::new(),
            true,
        ),
        tool_definition(
            "read_health",
            "Read workspace context readiness without mutating artifacts.",
            json!({}),
            Vec::new(),
            true,
        ),
        tool_definition(
            "graph_patch_apply",
            "Apply an agent-generated, evidence-backed graph patch to the current Etyma graph. The patch is validated against existing source and evidence refs before auto-apply.",
            json!({
                "agentId": { "type": "string", "description": "Optional calling agent identifier for audit records, such as codex, claudecode, or pi-agent." },
                "graphPatch": {
                    "type": "object",
                    "required": ["schemaVersion", "sourceIds", "evidenceRefs"],
                    "additionalProperties": false,
                    "properties": {
                        "schemaVersion": { "type": "string", "const": etyma_engine_types::GRAPH_PATCH_SCHEMA_VERSION },
                        "sourceIds": { "type": "array", "items": { "type": "string" }, "minItems": 1, "uniqueItems": true },
                        "evidenceRefs": { "type": "array", "items": { "type": "string" }, "minItems": 1, "uniqueItems": true },
                        "nodes": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "required": ["nodeId", "kind", "label"],
                                "additionalProperties": false,
                                "properties": {
                                    "nodeId": { "type": "string" },
                                    "kind": { "type": "string" },
                                    "label": { "type": "string" },
                                    "scope": { "type": "string" },
                                    "aliases": { "type": "array", "items": { "type": "string" } },
                                    "sourceIds": { "type": "array", "items": { "type": "string" } },
                                    "evidenceIds": { "type": "array", "items": { "type": "string" } }
                                }
                            }
                        },
                        "relations": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "required": ["relationId", "kind", "sourceNodeId", "targetNodeId"],
                                "additionalProperties": false,
                                "properties": {
                                    "relationId": { "type": "string" },
                                    "kind": { "type": "string" },
                                    "sourceNodeId": { "type": "string" },
                                    "targetNodeId": { "type": "string" },
                                    "label": { "type": "string" },
                                    "evidenceIds": { "type": "array", "items": { "type": "string" } }
                                }
                            }
                        },
                        "claims": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "required": ["claimId", "statement"],
                                "additionalProperties": false,
                                "properties": {
                                    "claimId": { "type": "string" },
                                    "statement": { "type": "string" },
                                    "topicRefs": { "type": "array", "items": { "type": "string" } },
                                    "sourceRefs": { "type": "array", "items": { "type": "string" } },
                                    "evidenceRefs": { "type": "array", "items": { "type": "string" } },
                                    "status": { "type": "string" }
                                }
                            }
                        },
                        "wikiPages": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "required": ["pageId", "path", "title", "body"],
                                "additionalProperties": false,
                                "properties": {
                                    "pageId": { "type": "string" },
                                    "path": { "type": "string" },
                                    "title": { "type": "string" },
                                    "body": { "type": "string" },
                                    "nodeRefs": { "type": "array", "items": { "type": "string" } },
                                    "sourceRefs": { "type": "array", "items": { "type": "string" } },
                                    "evidenceRefs": { "type": "array", "items": { "type": "string" } }
                                }
                            }
                        },
                        "agentMetadata": { "type": "object" }
                    }
                },
            }),
            vec!["graphPatch"],
            false,
        ),
        tool_definition(
            "write_propose",
            "Propose an evidence-backed knowledge item for approval. Evidence refs must exist in the current workspace snapshot.",
            json!({
                "contentType": { "type": "string", "enum": WRITE_CONTENT_TYPES, "description": "Supported evidence-backed write type." },
                "title": { "type": "string", "description": "Human-readable title for the knowledge item." },
                "body": { "type": "string", "description": "The knowledge content body." },
                "evidenceRefs": { "type": "array", "items": { "type": "string" }, "minItems": 1, "uniqueItems": true, "description": "Evidence IDs from the current workspace snapshot that back this knowledge item." },
            }),
            vec!["contentType", "title", "body", "evidenceRefs"],
            false,
        ),
        tool_definition(
            "write_commit",
            "Approve a pending proposal and persist it as an audited brain event. Pass userApproved=true only after explicit user approval for proposals that require it.",
            json!({
                "proposalId": { "type": "string", "pattern": PROPOSAL_ID_PATTERN, "description": "Proposal ID returned by write_propose." },
                "userApproved": { "type": "boolean", "description": "Set true only when the user explicitly approved a proposal marked as requiring approval." },
            }),
            vec!["proposalId"],
            false,
        ),
        tool_definition(
            "write_commit_all",
            "Approve multiple pending proposals in a single batch call.",
            json!({
                "proposalIds": { "type": "array", "items": { "type": "string", "pattern": PROPOSAL_ID_PATTERN }, "minItems": 1, "uniqueItems": true, "description": "Array of proposal IDs to commit." },
            }),
            vec!["proposalIds"],
            false,
        ),
        tool_definition(
            "write_list",
            "List all pending proposals.",
            json!({}),
            Vec::new(),
            true,
        ),
        tool_definition(
            "write_reject",
            "Reject a pending proposal and remove it from the proposals directory.",
            json!({
                "proposalId": { "type": "string", "pattern": PROPOSAL_ID_PATTERN, "description": "Proposal ID to reject." },
            }),
            vec!["proposalId"],
            false,
        ),
    ]
}

fn tool_definition(
    name: &str,
    description: &str,
    properties: Value,
    required: Vec<&str>,
    read_only: bool,
) -> Value {
    let mut merged_properties = properties.as_object().cloned().unwrap_or_default();
    merged_properties.insert(
        "workspaceId".into(),
        json!({
            "type": "string",
            "description": "Etyma workspace ID. Defaults to default."
        }),
    );
    merged_properties.insert(
        "rootDir".into(),
        json!({
            "type": "string",
            "description": "Optional development-only materialized workspace root. Disabled unless ETYMA_MCP_ALLOW_ROOT_DIR=1 and ETYMA_MCP_ALLOWED_ROOTS allow it."
        }),
    );
    if supports_local_path_disclosure(name) {
        merged_properties.insert(
            "includeLocalPaths".into(),
            json!({
                "type": "boolean",
                "description": "Include absolute local filesystem paths in responses only when the MCP server was started with ETYMA_MCP_ALLOW_LOCAL_PATHS=1. Defaults to false; keep false for agent-facing calls."
            }),
        );
    }

    let automation_policy = policy_for_mcp_tool(name);

    let mut annotations = json!({
        "readOnlyHint": read_only,
        "destructiveHint": automation_policy.destructive,
        "idempotentHint": read_only,
        "openWorldHint": false,
        "etymaAutomationPolicy": automation_policy_metadata(automation_policy)
    });
    if let Some(policy) = mutating_tool_policy(name) {
        annotations["etymaMutationPolicy"] = json!({
            "scopePolicy": policy.scope_policy,
            "evidencePolicy": policy.evidence_policy,
            "auditPolicy": policy.audit_policy,
            "replayPolicy": policy.replay_policy,
        });
    }

    json!({
        "name": name,
        "title": title_case_tool_name(name),
        "description": description,
        "inputSchema": {
            "type": "object",
            "properties": merged_properties,
            "required": required,
            "additionalProperties": false
        },
        "annotations": annotations
    })
}

fn automation_policy_metadata(policy: ToolAutomationPolicy) -> Value {
    json!({
        "automatic": policy.decision == AutomationDecision::Automatic,
        "requiresApproval": policy.decision == AutomationDecision::RequiresApproval,
        "destructive": policy.destructive,
        "approvalBoundary": "destructive_etyma_removal_or_overwrite",
        "reason": policy.reason
    })
}

pub(super) fn mutating_tool_policy(name: &str) -> Option<MutatingToolPolicy> {
    MUTATING_TOOL_POLICIES
        .iter()
        .copied()
        .find(|policy| policy.tool_name == name)
}

fn title_case_tool_name(name: &str) -> String {
    name.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => {
                    let mut title = first.to_ascii_uppercase().to_string();
                    title.push_str(chars.as_str());
                    title
                }
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}
