[package]
name = "duckdocs-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
ratatui.workspace = true
duckdocs-engine-client = { path = "../duckdocs-engine-client" }
duckdocs-engine-types = { path = "../duckdocs-engine-types" }
