[package]
name = "duckdocs-desktop"
version = "0.1.0"
edition = "2021"
description = "DuckDocs Tauri desktop shell"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
anyhow.workspace = true
base64.workspace = true
duckdocs-engine-client = { path = "../../../crates/duckdocs-engine-client" }
duckdocs-engine-types = { path = "../../../crates/duckdocs-engine-types" }
dirs.workspace = true
rfd = "0.15.4"
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
tauri = { version = "2.0.0", features = [] }
thiserror.workspace = true

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
