[package]
name = "hyprduck-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "hyprduck"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
ratatui.workspace = true
hyprduck-engine-client = { path = "../hyprduck-engine-client" }
hyprduck-engine-types = { path = "../hyprduck-engine-types" }
serde.workspace = true
serde_json.workspace = true
