use super::*;

pub(crate) fn compile_knowledge_project(
    request: &CompileProjectRequest,
    markdown: &str,
    source_manifest: Option<&SourceArtifactManifest>,
) -> KnowledgeProject {
    compile_agent_orchestrated_project(request, markdown, source_manifest)
}

pub(crate) fn compile_agent_orchestrated_project(
    request: &CompileProjectRequest,
    markdown: &str,
    source_manifest: Option<&SourceArtifactManifest>,
) -> KnowledgeProject {
    let title = infer_markdown_title(&request.source_markdown_path, markdown);
    let mut page_sections = extract_page_sections(markdown);
    attach_page_artifacts_to_sections(&mut page_sections, source_manifest);
    let source_path = request
        .source_document_path
        .clone()
        .unwrap_or_else(|| request.source_markdown_path.clone());
    let source_node_id = source_manifest
        .map(|manifest| source_node_id(&manifest.source_id))
        .unwrap_or_else(|| "document".into());
    let source_label = source_manifest
        .map(source_label_from_manifest)
        .unwrap_or_else(|| title.clone());
    let source_path_for_evidence = source_manifest
        .map(|manifest| manifest.source_path.clone())
        .unwrap_or_else(|| source_path.clone());
    let source_id_for_evidence = source_manifest.map(|manifest| manifest.source_id.clone());
    let project_id = source_manifest
        .map(|manifest| build_source_backed_project_id(&manifest.workspace_id, &manifest.source_id))
        .unwrap_or_else(|| build_project_id(request));

    let source_node = GraphNodeSummary {
        id: source_node_id.clone(),
        label: source_label.clone(),
        kind: source_manifest
            .map(|_| GraphNodeKind::Source)
            .unwrap_or(GraphNodeKind::Document),
        confidence: Some(0.72),
        related_count: 0,
        evidence_count: page_sections.len(),
        position: GraphNodePosition { x: 50.0, y: 50.0 },
    };
    let document_evidence = page_sections
        .iter()
        .take(8)
        .enumerate()
        .map(|(index, section)| EvidenceRef {
            id: source_id_for_evidence
                .as_deref()
                .map(|source_id| format!("ev-{source_id}-source-{}", index + 1))
                .unwrap_or_else(|| format!("ev-source-{}", index + 1)),
            page_label: section.page_label.clone(),
            page_index: Some(section.page_index),
            snippet: excerpt(&section.content, 220),
            source_path: Some(source_path_for_evidence.clone()),
            source_id: source_id_for_evidence.clone(),
            markdown_path: section.markdown_path.clone(),
            image_path: section.image_path.clone(),
            provenance: Some(format!(
                "Source evidence prepared from {}. Derived graph nodes, claims, and relations are generated by the graph maintenance agent.",
                section.page_label
            )),
        })
        .collect::<Vec<_>>();

    let mut details_by_node_id = BTreeMap::new();
    details_by_node_id.insert(
        source_node.id.clone(),
        GraphNodeDetail {
            node: source_node.clone(),
            canonical_name: source_label.clone(),
            aliases: vec![if source_manifest.is_some() {
                "Immutable source".into()
            } else {
                "Imported document".into()
            }],
            description: format!(
                "Source imported with {} visible evidence section(s). Derived graph nodes, claims, and relations are generated by graph maintenance, not compiler output.",
                page_sections.len()
            ),
            evidence: document_evidence.clone(),
            actions: source_node_actions(),
            source: source_manifest.map(source_backing_from_manifest),
        },
    );

    let mut answer_by_node_id = BTreeMap::new();
    answer_by_node_id.insert(
        source_node.id.clone(),
        AnswerResponse {
            status: AnswerStatus::LowConfidence,
            text: Some(
                "Source evidence is ready. The graph maintenance agent is responsible for deriving durable nodes, claims, and relations."
                    .into(),
            ),
            explanation:
                "HyprDuck keeps deterministic ingest limited to source and evidence preparation. Derived knowledge is produced by graph maintenance."
                    .into(),
            citations: document_evidence.clone(),
            related_node_ids: Vec::new(),
            suggested_actions: vec![SuggestedAction {
                kind: SuggestedActionKind::InspectEvidence,
                label: "Inspect source evidence".into(),
                description: "Review the source markdown evidence before using derived graph updates."
                    .into(),
            }],
        },
    );

    let nodes = vec![source_node];
    let evidence_count = document_evidence.len();

    KnowledgeProject {
        summary: ProjectOverview {
            project_id,
            title,
            status: ProjectStatus::Ready,
            stale: false,
            summary: format!(
                "Prepared source evidence from {} page sections. Derived graph generation is delegated to the graph maintenance agent.",
                page_sections.len()
            ),
            document_count: 1,
            node_count: nodes.len(),
            relationship_count: 0,
            evidence_count,
            hidden_concept_count: 0,
            hidden_relation_count: 0,
        },
        nodes,
        edges: Vec::new(),
        details_by_node_id,
        edge_details_by_id: BTreeMap::new(),
        answer_by_node_id,
    }
}
